# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec file for directory mode (one-dir)
# Used for creating installer packages
from PyInstaller.utils.hooks import collect_data_files, collect_submodules, collect_dynamic_libs

# Collect data files from packages
datas = []
datas += collect_data_files('customtkinter', include_py_files=False)
datas += collect_data_files('aioesphomeapi', include_py_files=False)
datas += collect_data_files('pymicro_wakeword', include_py_files=False)
datas += collect_data_files('soundcard', include_py_files=False)
datas += collect_data_files('pygame', include_py_files=False)
datas += collect_data_files('vlc', include_py_files=False)
datas += collect_data_files('webrtcvad', include_py_files=False)
datas += collect_data_files('zeroconf', include_py_files=False)

# Add source files
datas += [('src', 'src')]

# Collect binaries
binaries = []
binaries += collect_dynamic_libs('customtkinter')
binaries += collect_dynamic_libs('aioesphomeapi')
binaries += collect_dynamic_libs('pymicro_wakeword')
binaries += collect_dynamic_libs('soundcard')
binaries += collect_dynamic_libs('pygame')
binaries += collect_dynamic_libs('vlc')
binaries += collect_dynamic_libs('webrtcvad')

# Hidden imports
hiddenimports = [
    'customtkinter',
    'aioesphomeapi',
    'soundcard',
    'pygame',
    'vlc',
    'numpy',
    'psutil',
    'win10toast',
    'pymicro_wakeword',
    'webrtcvad',
    'zeroconf',
    'zeroconf._dns',
    'zeroconf._services',
    'zeroconf._services.info',
    'zeroconf._services.types',
    'zeroconf._cache',
    'zeroconf._core',
    'zeroconf._handlers',
    'zeroconf._protocol',
    'zeroconf._logger',
    'zeroconf._utils',
    'zeroconf._updates',
    'zeroconf._engine',
    'zeroconf._listener',
    'zeroconf._record',
    'zeroconf._transport',
    'zeroconf._resolver',
    'zeroconf._browser',
    'zeroconf._registration',
    'zeroconf._exceptions',
    'zeroconf._const',
    'zeroconf._asyncio',
    'ifaddr',
    'asyncio',
    'ipaddress',
    'socket',
    'selectors',
    'typing',
    'dataclasses',
    'weakref',
    'threading',
    'queue',
    'time',
    'random',
    'hashlib',
    'base64',
    'struct',
    'json',
    're',
    'collections',
    'collections.abc',
    'contextlib',
    'functools',
    'itertools',
    'operator',
    'copy',
    'pickle',
    'uuid',
    'datetime',
    'decimal',
    'fractions',
    'enum',
    'inspect',
    'importlib',
    'importlib.abc',
    'importlib.util',
    'importlib.machinery',
    'pathlib',
    'os',
    'sys',
    'io',
    'warnings',
    'traceback',
    'logging',
    'logging.handlers',
    'logging.config',
    'abc',
    'types',
    'typing_extensions',
    'typing_inspect',
    'pydantic',
    'pydantic_core',
    'pydantic.fields',
    'pydantic.main',
    'pydantic.validators',
    'pydantic.parse',
    'pydantic.json',
    'pydantic.utils',
    'pydantic.typing',
    'pydantic.version',
    'pydantic.errors',
    'pydantic.exceptions',
    'pydantic.types',
    'pydantic.dataclasses',
    'pydantic.functional_validators',
    'pydantic.annotated_handlers',
    'pydantic._internal',
    'pydantic._internal._config',
    'pydantic._internal._fields',
    'pydantic._internal._model_construction',
    'pydantic._internal._model_serialization',
    'pydantic._internal._repr',
    'pydantic._internal._utils',
    'pydantic._internal._validation_serialization',
    'pydantic._internal._std_types_schema',
    'pydantic._internal._dataclasses',
    'pydantic._internal._generate_schema',
    'pydantic._internal._core_utils',
    'pydantic._internal._core_metadata',
    'pydantic._internal._core_validation',
    'pydantic._internal._core_serialization',
    'pydantic._internal._decorators',
    'pydantic._internal._config',
    'pydantic._internal._model_construction',
    'pydantic._internal._model_serialization',
    'pydantic._internal._repr',
    'pydantic._internal._utils',
    'pydantic._internal._validation_serialization',
    'pydantic._internal._std_types_schema',
    'pydantic._internal._dataclasses',
    'pydantic._internal._generate_schema',
    'pydantic._internal._core_utils',
    'pydantic._internal._core_metadata',
    'pydantic._internal._core_validation',
    'pydantic._internal._core_serialization',
    'pydantic._internal._decorators',
    'pydantic_core._pydantic_core',
    'pydantic_core.core_schema',
    'pydantic_core.core_utils',
    'pydantic_core.types',
    'pydantic_core.validators',
    'pydantic_core._pydantic_core',
    'annotated_types',
    'attrs',
    'attrs._cmp',
    'attrs._config',
    'attrs._funcs',
    'attrs._make',
    'attrs._version_info',
    'attrs._next_gen',
    'attrs.converters',
    'attrs.exceptions',
    'attrs.fields',
    'attrs.filters',
    'attr',
    'attr._cmp',
    'attr._config',
    'attr._funcs',
    'attr._make',
    'attr._version_info',
    'attr._next_gen',
    'attr.converters',
    'attr.exceptions',
    'attr.filters',
    'attr.validators',
    'attr._validators',
    'pycaw',
    'pycaw.pycaw',
    'pycaw.utils',
    'pycaw.constants',
    'comtypes',
    'comtypes.client',
    'comtypes.client._generate',
    'comtypes.client._events',
    'comtypes.client.dynamic',
    'comtypes.client.lazybind',
    'comtypes.client.wrap',
    'comtypes.automation',
    'comtypes.connectionpoints',
    'comtypes.errorinfo',
    'comtypes.gen',
    'comtypes.hresult',
    'comtypes.persist',
    'comtypes.server',
    'comtypes.server.automation',
    'comtypes.server.connectionpoints',
    'comtypes.server.register',
    'comtypes.server.stdmethods',
    'comtypes.typeinfo',
    'comtypes.util',
    'PIL',
    'PIL.Image',
    'PIL.ImageTk',
    'PIL.ImageDraw',
    'PIL.ImageFont',
    'PIL.ImageFilter',
    'PIL.ImageEnhance',
    'PIL.ImageOps',
    'PIL.ImageColor',
    'PIL.ImageSequence',
    'PIL.ImageCms',
    'PIL.ImagePalette',
    'PIL.ImageMode',
    'PIL.ImageStat',
    'PIL.ImageWin',
    'PIL.GifImagePlugin',
    'PIL.JpegImagePlugin',
    'PIL.PngImagePlugin',
    'PIL.BmpImagePlugin',
    'PIL.TiffImagePlugin',
    'PIL.WebPImagePlugin',
    'PIL.IcoImagePlugin',
    'pystray',
    'pystray._util',
    'pystray._base',
    'pystray._win32',
    'pystray._appindicator',
    'pystray._darwin',
    'pystray._gtk',
    'pystray._dummy',
    'pystray.icons',
    'win10toast',
    'win10toast.toast',
    'win10toast.toastWindows',
    'windows_toasts',
    'windows_toasts.windows_toasts',
    'windows_toasts.interop',
    'windows_toasts.audios',
    'windows_toasts.events',
    'windows_toasts.adapters',
    'windows_toasts.sources',
    # src modules
    'src.i18n',
    'src.core.mdns_discovery',
    'src.core.esphome_protocol',
    'src.ui.system_tray_icon',
    'src.voice.audio_recorder',
    'src.voice.mpv_player',
    'src.voice.wake_word',
    'src.voice.vad',
    'src.voice.voice_assistant',
    'src.commands.command_executor',
    'src.commands.system_commands',
    'src.commands.media_commands',
    'src.commands.audio_commands',
    'src.sensors.windows_monitor',
    'src.notify.announcement',
    'src.notify.toast_notification',
    'src.notify.service_entity',
    'src.ui.main_window',
    'src.autostart',
    # Collect all submodules
    *collect_submodules('customtkinter'),
    *collect_submodules('aioesphomeapi'),
    *collect_submodules('pymicro_wakeword'),
    *collect_submodules('soundcard'),
    *collect_submodules('pygame'),
    *collect_submodules('vlc'),
    *collect_submodules('zeroconf'),
    *collect_submodules('ifaddr'),
    *collect_submodules('pydantic'),
    *collect_submodules('pydantic_core'),
    *collect_submodules('attrs'),
    *collect_submodules('comtypes'),
    *collect_submodules('PIL'),
    *collect_submodules('pystray'),
    *collect_submodules('win10toast'),
    *collect_submodules('windows_toasts'),
]

a = Analysis(
    ['src\\__main__.py'],
    pathex=[],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=['hooks'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['matplotlib', 'pandas', 'scipy', 'pytest', 'tkinter'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='HomeAssistantWindows',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    version='version_info.txt',
    icon=['src\\logo.ico'],
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='HomeAssistantWindows',
)